spring:
  application:
    name: Clinic-management-system
  datasource:
    url: jdbc:mysql://localhost:3306/cms?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
        ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: isaacsteverado9@gmail.com
    password: zypaqnwpskhvqcfq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #catch errors
  mvc:
    throw-exception-if-no-handler-found: true
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 9090

#logging to see hibernate intended queries
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

